import { createHmac, randomUUID, timingSafeEqual } from "node:crypto";
import { createPublicServerClient } from "@/lib/supabase/public-server";
import { logApiError } from "@/lib/server/api";
import type { ContentItem, ContentType } from "@/types/database";

const PAGE_SIZE = 20;
const CURSOR_VERSION = "catalog-search-v2";
const HIGHLIGHT_START = "<<NF_HL>>";
const HIGHLIGHT_END = "<</NF_HL>>";

export type CatalogSearchOutcome = "results" | "no_results" | "input_empty";

export type CatalogSearchResult = ContentItem & {
    snippet: {
        source: string;
        text: string;
        highlights: Array<{ start: number; end: number }>;
    };
    rank: number;
};

export type CatalogSearchResponse = {
    outcome: CatalogSearchOutcome;
    results: CatalogSearchResult[];
    pageInfo: {
        nextCursor: string | null;
        previousCursor: string | null;
        page: number;
    };
};

type CursorDirection = "after" | "before";
type CatalogSearchCursor = {
    version: typeof CURSOR_VERSION;
    queryHash: string;
    categories: string[];
    type: ContentType | null;
    direction: CursorDirection;
    // PostgreSQL's shortest float representation round-trips to the same
    // stored real value. Keeping it textual avoids JavaScript rounding a
    // keyset boundary before it returns to PostgreSQL.
    rank: string;
    contentId: string;
    page: number;
};

type SearchRow = {
    query_state: "results" | "input_empty";
    content_id: string | null;
    content_type: ContentType | null;
    title: string | null;
    author: string | null;
    category: string | null;
    cover_image_url: string | null;
    duration_seconds: number | null;
    audio_url: string | null;
    created_at: string | null;
    quick_mode_json: ContentItem["quick_mode_json"];
    result_rank: number | null;
    cursor_rank: string | null;
    snippet_source: string | null;
    snippet_headline: string | null;
};

export class CatalogSearchError extends Error {
    constructor(
        public readonly code: "CURSOR_INVALID" | "UNAVAILABLE",
        message: string,
        public readonly requestId?: string,
    ) {
        super(message);
    }
}

export function normalizeCatalogSearchQuery(value: string | undefined) {
    return (value ?? "").trim().replace(/\s+/g, " ").slice(0, 160);
}

function cursorSecret() {
    const secret = process.env.CATALOG_SEARCH_CURSOR_SECRET;
    if (!secret) throw new CatalogSearchError("UNAVAILABLE", "Catalog search is not configured.");
    return secret;
}

function contextHash(query: string, categories: string[], type: ContentType | null) {
    return createHmac("sha256", cursorSecret())
        .update(JSON.stringify({ query, categories, type, version: CURSOR_VERSION }))
        .digest("base64url");
}

function encodeCursor(cursor: CatalogSearchCursor) {
    const payload = Buffer.from(JSON.stringify(cursor)).toString("base64url");
    const signature = createHmac("sha256", cursorSecret()).update(payload).digest("base64url");
    return `${payload}.${signature}`;
}

function decodeCursor(value: string, queryHash: string, categories: string[], type: ContentType | null) {
    const [payload, signature] = value.split(".");
    if (!payload || !signature) throw new CatalogSearchError("CURSOR_INVALID", "This search cursor is invalid. Start again.");
    const expected = createHmac("sha256", cursorSecret()).update(payload).digest("base64url");
    const supplied = Buffer.from(signature);
    const expectedBytes = Buffer.from(expected);
    if (supplied.length !== expectedBytes.length || !timingSafeEqual(supplied, expectedBytes)) {
        throw new CatalogSearchError("CURSOR_INVALID", "This search cursor is invalid. Start again.");
    }

    let cursor: CatalogSearchCursor;
    try {
        cursor = JSON.parse(Buffer.from(payload, "base64url").toString("utf8")) as CatalogSearchCursor;
    } catch {
        throw new CatalogSearchError("CURSOR_INVALID", "This search cursor is invalid. Start again.");
    }

    if (
        cursor.version !== CURSOR_VERSION
        || cursor.queryHash !== queryHash
        || JSON.stringify(cursor.categories) !== JSON.stringify(categories)
        || cursor.type !== type
        || (cursor.direction !== "after" && cursor.direction !== "before")
        || typeof cursor.rank !== "string"
        || !Number.isFinite(Number(cursor.rank))
        || typeof cursor.contentId !== "string"
        || !Number.isInteger(cursor.page)
        || cursor.page < 1
    ) {
        throw new CatalogSearchError("CURSOR_INVALID", "This search cursor is invalid. Start again.");
    }
    return cursor;
}

export function parseCatalogSearchHeadline(value: string) {
    const highlights: Array<{ start: number; end: number }> = [];
    let text = "";
    let cursor = 0;

    // Markers are server-generated by ts_headline. Treat malformed marker pairs
    // as ordinary text so a bad snippet can never produce unsafe HTML or offsets.
    while (cursor < value.length) {
        const start = value.indexOf(HIGHLIGHT_START, cursor);
        if (start === -1) {
            text += value.slice(cursor);
            break;
        }

        text += value.slice(cursor, start);
        const end = value.indexOf(HIGHLIGHT_END, start + HIGHLIGHT_START.length);
        if (end === -1) {
            text += value.slice(start + HIGHLIGHT_START.length);
            break;
        }

        const matchingText = value.slice(start + HIGHLIGHT_START.length, end);
        const highlightStart = text.length;
        text += matchingText;
        if (matchingText.length > 0) {
            highlights.push({ start: highlightStart, end: text.length });
        }
        cursor = end + HIGHLIGHT_END.length;
    }

    const truncatedText = text.slice(0, 280);
    return {
        text: truncatedText,
        highlights: highlights
            .filter((highlight) => highlight.start < truncatedText.length)
            .map((highlight) => ({ ...highlight, end: Math.min(highlight.end, truncatedText.length) })),
    };
}

export async function searchCatalog(input: {
    query: string;
    categories?: string[] | null;
    type?: ContentType | null;
    cursor?: string | null;
}): Promise<CatalogSearchResponse> {
    const query = normalizeCatalogSearchQuery(input.query);
    const categories = [...new Set((input.categories ?? []).map((category) => category.trim()).filter(Boolean))].sort();
    const type = input.type ?? null;
    const hash = contextHash(query, categories, type);
    const cursor = input.cursor ? decodeCursor(input.cursor, hash, categories, type) : null;
    const client = createPublicServerClient() as unknown as {
        rpc: (name: string, args: Record<string, unknown>) => Promise<{ data: SearchRow[] | null; error: { message: string } | null }>;
    };
    const { data, error } = await client.rpc("search_catalog", {
        p_query: query,
        p_categories: categories,
        p_type: type,
        p_after_rank: cursor?.direction === "after" ? cursor.rank : null,
        p_after_content_id: cursor?.direction === "after" ? cursor.contentId : null,
        p_before_rank: cursor?.direction === "before" ? cursor.rank : null,
        p_before_content_id: cursor?.direction === "before" ? cursor.contentId : null,
        p_limit: PAGE_SIZE + 1,
    });
    if (error) {
        const requestId = randomUUID();
        logApiError({
            requestId,
            route: "catalog-search-module",
            message: "Catalog search database call failed",
            error,
        });
        throw new CatalogSearchError("UNAVAILABLE", "Catalog search is temporarily unavailable.", requestId);
    }
    if (data?.[0]?.query_state === "input_empty") {
        return { outcome: "input_empty", results: [], pageInfo: { nextCursor: null, previousCursor: null, page: 1 } };
    }

    const rawRows = cursor?.direction === "before" ? [...(data ?? [])].reverse() : data ?? [];
    const hasMore = rawRows.length > PAGE_SIZE;
    const rows = rawRows.slice(0, PAGE_SIZE).filter((row): row is SearchRow & { content_id: string; content_type: ContentType; title: string; created_at: string; result_rank: number; cursor_rank: string } => (
        row.query_state === "results" && Boolean(row.content_id && row.content_type && row.title && row.created_at && row.result_rank !== null && row.cursor_rank)
    ));
    const page = cursor?.direction === "before" ? Math.max(1, cursor.page - 1) : (cursor?.page ?? 1);
    const results = rows.map((row) => ({
        id: row.content_id,
        type: row.content_type,
        title: row.title,
        author: row.author,
        category: row.category,
        cover_image_url: row.cover_image_url,
        duration_seconds: row.duration_seconds,
        audio_url: row.audio_url,
        created_at: row.created_at,
        quick_mode_json: row.quick_mode_json,
        embedding: null,
        hero_image_url: null,
        is_featured: false,
        narration_completed_at: null,
        narration_error: null,
        narration_requested_at: null,
        narration_started_at: null,
        narration_status: "idle",
        published_at: null,
        series_id: null,
        series_order: null,
        source_url: null,
        status: "verified" as const,
        updated_at: row.created_at,
        deleted_at: null,
        rank: row.result_rank,
        snippet: { source: row.snippet_source ?? "Summary", ...parseCatalogSearchHeadline(row.snippet_headline ?? row.title) },
    }));
    const first = rows.at(0);
    const last = rows.at(-1);
    return {
        outcome: results.length > 0 ? "results" : "no_results",
        results,
        pageInfo: {
            nextCursor: hasMore && last ? encodeCursor({ version: CURSOR_VERSION, queryHash: hash, categories, type, direction: "after", rank: last.cursor_rank, contentId: last.content_id, page: page + 1 }) : null,
            previousCursor: page > 1 && first ? encodeCursor({ version: CURSOR_VERSION, queryHash: hash, categories, type, direction: "before", rank: first.cursor_rank, contentId: first.content_id, page }) : null,
            page,
        },
    };
}
